# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Choose a zsh theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Enabled plugins
plugins=(git python pip gcloud zsh-autosuggestions zsh-syntax-highlighting)

# Load oh-myzsh
source "${ZSH}"/oh-my-zsh.sh

# Load alias for commands
source "${HOME}"/.zshrc_aliases

# Load environment variables
source "${HOME}"/.zshrc_variables

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

